version: "3.8"
services:
  backend:
    container_name: backend
    image: sunkarisomasekhar/task-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=dev
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: sunkarisomasekhar/task-frontend:latest  

    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
